---
# Nginx Configuration
nginx_version: "1.27"
nginx_user: "www-data"
nginx_group: "www-data"

nginx_worker_processes: "{{ nginx_worker_processes | default('auto') }}"
nginx_worker_connections: "{{ nginx_worker_connections | default(1024) }}"
nginx_multi_accept: "on"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "{{ nginx_client_max_body_size | default('64m') }}"
nginx_client_body_buffer_size: "128k"
nginx_client_header_buffer_size: "1k"
nginx_large_client_header_buffers: "4 4k"
nginx_client_body_timeout: "12"
nginx_client_header_timeout: "12"
nginx_send_timeout: "10"

# SSL Configuration
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
nginx_ssl_prefer_server_ciphers: "off"
nginx_ssl_session_cache: "shared:SSL:10m"
nginx_ssl_session_timeout: "10m"

# ModSecurity Configuration
modsecurity_enabled: true
modsecurity_audit_log: "/var/log/modsec_audit.log"
modsecurity_rules_dir: "/etc/nginx/modsec"

# OWASP Core Rule Set
owasp_crs_version: "3.3.4"
owasp_crs_url: "https://github.com/coreruleset/coreruleset/archive/v{{ owasp_crs_version }}.tar.gz"

# Gzip Configuration
nginx_gzip: "on"
nginx_gzip_vary: "on"
nginx_gzip_proxied: "any"
nginx_gzip_comp_level: "6"
nginx_gzip_types:
  - "text/plain"
  - "text/css"
  - "text/xml"
  - "text/javascript"
  - "application/json"
  - "application/javascript"
  - "application/xml+rss"
  - "application/atom+xml"
  - "image/svg+xml"

# Rate Limiting
nginx_rate_limit_zone: "magento"
nginx_rate_limit: "10r/s"
nginx_rate_limit_burst: "20"

# Security Headers
nginx_security_headers:
  - "X-Frame-Options SAMEORIGIN"
  - "X-Content-Type-Options nosniff"
  - "X-XSS-Protection \"1; mode=block\""
  - "Referrer-Policy strict-origin-when-cross-origin"
  - "Permissions-Policy geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
