---
- name: Install RabbitMQ signing key
  apt_key:
    url: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
    state: present
  become: yes

- name: Add RabbitMQ repository
  apt_repository:
    repo: "deb https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_distribution_release }} main"
    state: present
  become: yes

- name: Install Erlang and RabbitMQ
  apt:
    name:
      - erlang
      - rabbitmq-server
    state: present
    update_cache: yes
  become: yes

- name: Enable RabbitMQ management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  become: yes

- name: Start and enable RabbitMQ
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: yes

- name: Create RabbitMQ vhost for Magento
  rabbitmq_vhost:
    name: "{{ rabbitmq_vhost }}"
    state: present
  become: yes

- name: Create RabbitMQ user for Magento
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    vhost: "{{ rabbitmq_vhost }}"
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present
  become: yes
