---
- name: Download Composer installer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "/tmp/composer-installer.php"
    mode: '0644'

- name: Install Composer
  command: "php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer --version={{ composer_version }}"
  become: yes
  creates: "{{ composer_install_path }}"

- name: Set Composer permissions
  file:
    path: "{{ composer_install_path }}"
    mode: '0755'
    owner: root
    group: root
  become: yes

- name: Configure Composer for magento user
  file:
    path: "/home/{{ system_user }}/.composer"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: '0755'
  become: yes

- name: Verify Composer installation
  command: composer --version
  register: composer_version_output
  changed_when: false

- name: Display Composer version
  debug:
    msg: "{{ composer_version_output.stdout }}"
