---
# PHP Default Configuration
php_versions:
  - "8.4"
  - "8.3"

php_default_version: "8.4"

# PHP Extensions required for Magento 2.4.8
# Note: Most extensions are built into PHP 8.4 core and automatically loaded
php_extensions:
  - php{{ php_default_version }}-fpm
  - php{{ php_default_version }}-cli

# PHP-FPM Configuration
php_fpm_listen: "/run/php/php{{ php_default_version }}-fpm.sock"
php_fpm_listen_owner: "www-data"
php_fpm_listen_group: "www-data"
php_fpm_listen_mode: "0660"

# PHP Configuration
php_memory_limit: "2G"
php_max_execution_time: "1800"
php_max_input_time: "1800"
php_max_input_vars: "1000"
php_post_max_size: "64M"
php_upload_max_filesize: "64M"
php_max_file_uploads: "20"
php_date_timezone: "America/Los_Angeles"

# OPcache Configuration
php_opcache_enable: 1
php_opcache_memory_consumption: 512
php_opcache_interned_strings_buffer: 64
php_opcache_max_accelerated_files: 60000
php_opcache_revalidate_freq: 2
php_opcache_validate_timestamps: 1
